# Generated by Django 6.1.1 on 2026-09-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('rating', models.FloatField(default=0)),
                ('pages', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('summary', models.TextField()),
                ('characters', models.CharField(blank=True, max_length=500)),
                ('themes', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
